#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/cupsd

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -f
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall cupsd
}

reload_service() {
    killall -HUP cupsd
}

boot() {
    start
}
